spring:
  application:
    name: microservice
eureka:
  instance:
    # Eureka? ??? ???? ID. ???? ??, ??? ??? IP/?? ??? ???.
    instance-id: localhost:8080
    prefer-ip-address: true # ???? ??? ?? ?? IP ??? ???? ??
    lease-renewal-interval-in-seconds: 5 # ???? ?? ??
    lease-expiration-duration-in-seconds: 15 # ???? ?? ??

  client:
    register-with-eureka: true # Eureka ??? ? ???? ??
    fetch-registry: true       # Eureka ???? ?? ????? ??? ???
    service-url:
      # Eureka ??? ??? ??. ???? ?? ??????? ?? ??? ???.
      defaultZone: http://localhost:8761/eureka/
