spring:
  application:
    name: discovery

server:
  port: 8761
eureka:
  instance:
    hostname: localhost # ?? ??? ?? (?? ??)
  client:
    register-with-eureka: false # Eureka ??? ??? ?????? ???? ??
    fetch-registry: false       # Eureka ??? ?????? ???? ??
    service-url:
      defaultZone: http://localhost:8761/eureka/ # ?????? ??? ?? ??

  server:
    enable-self-preservation: true # ?? ?? ?? ??? (???? ?? ? ??)
    eviction-interval-timer-in-ms: 10000 # ???? ?? ??
